#!/bin/bash

download_range()
{
    start="$1"
    end="$2"

    for i in $(seq -f "%04g" "$start" "$end"); do
        ./client "in-data/file$i" "out-data/file$i"
    done
}

mkdir out-data > /dev/null 2>&1
for i in $(seq 0 10); do
    download_range $((${i}*1000)) $((${i}*100+999)) &
done
wait
